apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    artifact.spinnaker.io/location: iboh
    artifact.spinnaker.io/name: api-gateway
    artifact.spinnaker.io/type: kubernetes/deployment
    moniker.spinnaker.io/application: apigateway
    moniker.spinnaker.io/cluster: deployment api-gateway
  creationTimestamp: 2018-09-24T11:26:37Z
  labels:
    app: api-gateway
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: apigateway
  name: api-gateway
  namespace: iboh
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        artifact.spinnaker.io/location: iboh
        artifact.spinnaker.io/name: api-gateway
        artifact.spinnaker.io/type: kubernetes/deployment
        moniker.spinnaker.io/application: apigateway
        moniker.spinnaker.io/cluster: deployment api-gateway
      creationTimestamp: null
      labels:
        app: api-gateway
        app.kubernetes.io/managed-by: spinnaker
        app.kubernetes.io/name: apigateway
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-dev-iboh-configmap
        - secretRef:
            name: env-dev-iboh-secrets
        image: gcr.io/ibohcloud/api-gateway
        imagePullPolicy: IfNotPresent
        name: api-gateway
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/secrets/iboh
          name: iboh-cloud-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: iboh-cloud-key
        secret:
          defaultMode: 420
          secretName: ibohdevcloud
